### ISSUE TITLE
The curl package

### ISSUE THREAD

**Issue by jeroen** [kalibera/cran-checks#1]
I am trying to understand some [warnings](https://github.com/kalibera/cran-checks/blob/master/rchk/results/curl.out) in the `curl` package. I hope that discussing this here might benefit others as well. This version concerns [curl_2.7](https://github.com/cran/curl/tree/2.7). The first warning is about [`handle.c`](https://github.com/cran/curl/blob/2.7/src/handle.c#L151)

```
Function R_handle_setopt
  [UP] unprotected variable optnames while calling allocating function Rf_asInteger curl/src/handle.c:203
  [UP] unprotected variable optnames while calling allocating function Rf_asReal curl/src/handle.c:223
```

The only place where `R_handle_setopt` is invoked is via `.Call()` and therefore `SEXP values` should automatically be protected. As I undertand it, this also protects all the elements and attributes of `values`. So why does this need a protect? Does `getAttrib()` make a copy??

```c
SEXP optnames = getAttrib(values, R_NamesSymbol);
```

In addition I don't understand why `Rf_asInteger()` is called an allocation function? I assumed this to be a readonly function, shorthand for `INTEGER(x)[0]`.

**Comment by kalibera** [comment]
Function `getAttrib(values, R_NamesSymbol)` may return a fresh unprotected object. This will happen e.g. when `values` is a pairlist. It may be that your function only gets called with such types of `values` for which `getAttrib` currently would return a reference to an object already protected via `values`, but the tool doesn't know and cannot know and it is better not to depend on that, also because the internal implementation of `getAttrib` may change. So yes, the warning is based on that `getAttrib` under some circumstances makes a copy. 

Yes, `Rf_asInteger` may allocate. It allocates when it prints a warning. The safe and robust way to write code is to assume that any function allocates also because this may change. If unsure, definitely one should protect.
