### ISSUE TITLE
rsparse package

### ISSUE THREAD

**Issue by dselivanov** [kalibera/cran-checks#2]
Hi Tomas. Thanks for all your great work. 
I'm trying to debug issue with my `rsparse` package and as suggested i'm running:
```
export R_CHECK_CONSTANTS=5
R CMD check rsparse_0.3.3.2.tar.gz
```

However I'm getting:

>* using log directory ‘/home/dselivanov/projects/rsparse/rsparse.Rcheck’
>* using R version 3.6.0 (2019-04-26)
>* using platform: x86_64-pc-linux-gnu (64-bit)
>* using session charset: UTF-8
>Error in readBin(con, "raw", n = 512L) :
  cannot get ALTVEC DATAPTR during GC
>Execution halted

Any ideas on what I'm doing wrong (with `R_CHECK_CONSTANTS=1` it works fine)? 

Thanks in advance.

**Comment by kalibera** [comment]
Hi Dmitriy,

I am sorry but this is due to a bug in 3.6.0 (interaction between constants checking and ALTREP, which no longer allows constants checking to be run from GC). I've fixed recently and I will update the readme for rcnst. If you need to reproduce on your end, please try with latest R-devel (build from source or if you are on Windows you can use a daily snapshot). Also you can try if you could reproduce the rcnst messages about rsparse using a level of R_CHECK_CONSTANTS smaller than 5 even using R 3.6.0. The CRAN checks for rcnst are run with R-devel.

Best
Tomas
